"""Add AnalysisJob and AnalyzedClip models

Revision ID: 171e1fbbffa2
Revises: 287c248ec752
Create Date: 2026-06-16 16:57:24.482010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171e1fbbffa2'
down_revision: Union[str, Sequence[str], None] = '287c248ec752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
