"""add_project_name_and_platform_remove_directives

Revision ID: 27ff8b7f29fa
Revises: 3692a148bdd0
Create Date: 2026-06-17 13:53:30.111121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ff8b7f29fa'
down_revision: Union[str, Sequence[str], None] = '3692a148bdd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', sa.String(), nullable=False, server_default=sa.text("'untitled-project'")))
    
    # Create the Enum type in the database
    platform_type = sa.Enum('INSTAGRAM_STORY', 'INSTAGRAM_REELS', 'YOUTUBE_SHORTS', 'TIKTOK', name='platformtype')
    platform_type.create(op.get_bind(), checkfirst=True)
    
    op.add_column('projects', sa.Column('platform', platform_type, nullable=True))
    op.drop_column('projects', 'directives')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('directives', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('projects', 'platform')
    
    # Drop the Enum type from the database
    platform_type = sa.Enum('INSTAGRAM_STORY', 'INSTAGRAM_REELS', 'YOUTUBE_SHORTS', 'TIKTOK', name='platformtype')
    platform_type.drop(op.get_bind(), checkfirst=True)
    
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###

