"""add_media_asset_metadata_fields

Revision ID: 3692a148bdd0
Revises: 623a1a3771bd
Create Date: 2026-06-17 12:40:52.959494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3692a148bdd0'
down_revision: Union[str, Sequence[str], None] = '623a1a3771bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('fps', sa.Float(), nullable=True))
    op.add_column('media_assets', sa.Column('total_frames', sa.Integer(), nullable=True))
    op.add_column('media_assets', sa.Column('is_image', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_assets', 'is_image')
    op.drop_column('media_assets', 'total_frames')
    op.drop_column('media_assets', 'fps')
    op.drop_column('media_assets', 'height')
    op.drop_column('media_assets', 'width')
    # ### end Alembic commands ###
