"""add final_video_key to AnalysisJob

Revision ID: 573b0bd68599
Revises: 07130787d3ba
Create Date: 2026-06-18 13:04:07.575950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573b0bd68599'
down_revision: Union[str, Sequence[str], None] = '07130787d3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('final_video_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'final_video_key')
    # ### end Alembic commands ###
