"""remove_platform_from_project

Revision ID: 88d27fe0eb1d
Revises: a992d2cd029d
Create Date: 2026-06-18 13:43:36.272326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88d27fe0eb1d'
down_revision: Union[str, Sequence[str], None] = 'a992d2cd029d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('platform', postgresql.ENUM('INSTAGRAM_STORY', 'INSTAGRAM_REELS', 'YOUTUBE_SHORTS', 'TIKTOK', name='platformtype'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
