"""add_vibe_to_analysis_jobs

Revision ID: d4f2b7ed1887
Revises: 623a1a3771bd
Create Date: 2026-06-17 14:30:15.545726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f2b7ed1887'
down_revision: Union[str, Sequence[str], None] = '623a1a3771bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('vibe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'vibe')
    # ### end Alembic commands ###
