"""Add missing columns to analysis_jobs

Revision ID: f39672b9371d
Revises: 88d27fe0eb1d
Create Date: 2026-06-24 17:19:09.559096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f39672b9371d'
down_revision: Union[str, Sequence[str], None] = '88d27fe0eb1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('directives', sa.Text(), nullable=True))
    op.add_column('analysis_jobs', sa.Column('music_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('analysis_jobs', 'final_video_key')
    op.drop_column('projects', 'platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('platform', postgresql.ENUM('INSTAGRAM_STORY', 'INSTAGRAM_REELS', 'YOUTUBE_SHORTS', 'TIKTOK', name='platformtype'), autoincrement=False, nullable=True))
    op.add_column('analysis_jobs', sa.Column('final_video_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('analysis_jobs', 'music_config')
    op.drop_column('analysis_jobs', 'directives')
    # ### end Alembic commands ###
